# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171129_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
