# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 02:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171130_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Field must be mimimum 2 characters and only letters', regex='^[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Field must be mimimum 2 characters and only letters', regex='^[a-zA-Z]{2,}$')]),
        ),
    ]
